# version: '3.9'

services:
  backend:
    build:
       context: ./backend
       dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/backend
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/backend/database/database.sqlite

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true