version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/backend/database/database.sqlite
    networks:
      - etterem-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    networks:
      - etterem-network

networks:
  etterem-network:
